print('введите первое число')
x= float(input())
print('введите второе число')
y= float(input())
print('Результаты:')
print('сложение', x+y)
print('вычитание', x-y)
print('умножение', x*y)
print('деление, кроме 0', x/y)